server:
  port: 8082

spring:
  application:
    name: Product


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default_Zone: http://localhost:8761/eureka
