server:
  port: 8080

spring:
  application:
    name: SCG
  cloud:
    gateway:
      routes:
        - id: User
          uri: lb://User
          predicates:
            - Path=/user/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default_Zone: http://localhost:8761/eureka
