server:
  port: 8083

spring:
  application:
    name: Cart
  datasource:
    url: jdbc:h2:mem:cartdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    h2:
      console:
        enabled: true
        path: /h2-console
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default_Zone: http://localhost:8761/eureka